In [1]:
import numpy as np

### Question 1
Write a function to create a Vandermonde matrix given an input vector and a boolean argument for increasing or decreasing.   

Note: I'm assuming that these matrices are always square - so that the powers go from 0 to n-1.

In [2]:
# solution 1 using the numpy vander function
def np_vander(a, increasing=True):
    return np.vander(a, a.shape[0], increasing)

v = np.array([1,2,6,9])
print(np_vander(v, True))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   6  36 216]
 [  1   9  81 729]]


In [3]:
# solution 2 without numpy's vander function
def la_vander(a, increasing=True):
    base = v.reshape(-1,1)
    to = np.arange(base.shape[0]).reshape(1,-1)
    vander = np.power(base,to)
    return vander if increasing else np.flip(vander, axis=1)

print(la_vander(v,False))

[[  1   1   1   1]
 [  8   4   2   1]
 [216  36   6   1]
 [729  81   9   1]]


### Question 2
Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
w = np.array([10,20,30,40,50,60,70,80,90,100])

In [5]:
# solution 1 using cumsum
def moving_av_csum (a, k=3):
    csum = np.cumsum(a)
    csum[k:] = csum[k:] - csum[:-k]
    return csum[k - 1:] / k

moving_av_csum(w)

array([20., 30., 40., 50., 60., 70., 80., 90.])

In [6]:
# solution 2 using convolutions
def moving_av_convolve (a, k=3):
    a = a.flatten()
    ones = np.ones(k,)
    return np.convolve(a,ones, mode="valid") / k

moving_av_convolve(w)

array([20., 30., 40., 50., 60., 70., 80., 90.])